### ISSUE TITLE
✨ 게시물 좋아요 기능 추가 요청

### ISSUE THREAD

**Issue by kyeongb-bin** [KJLBK/danum-backend#159]
## :sparkles: 어떤 기능인가요?
사용자는 게시물에 좋아요를 누르거나 취소할 수 있으면 좋을 거 같습니다. 
특정 게시물의 좋아요 개수도 보여지면 좋을 거 같습니다. 
아래 내용은 ChatGPT를 참고하여 작성하였습니다.

### 1. 특정 게시물에 좋아요를 추가하는 기능입니다.
POST /board/question/like/{id}

요청:
```
{
  "userId": "사용자 ID",
  "likeStatus": true
}
```
응답:
```
{
  "message": "좋아요가 등록되었습니다.",
  "likeCount": 42
}
```

### 2. 특정 게시물에 대한 좋아요를 취소하는 기능입니다.
DELETE /board/question/like/{id}

요청:
```
{
  "userId": "사용자 ID",
  "likeStatus": false
}
```
응답:
```
{
  "message": "좋아요가 취소되었습니다.",
  "likeCount": 41
}
```

### 3. 특정 게시물의 총 좋아요 수와 사용자가 해당 게시물을 좋아요 했는지 여부를 가져오는 기능입니다.
GET /board/question/likes/{id}

응답:
```
{
  "likeCount": 42,
  "isLikedByUser": true
}
```

**Comment by alpin87** [comment]
1. 특정 게시물에 좋아요를 추가하는 기능
이미 /board/question/like/{id} 로 구현되어있음.

2. 특정 게시물에 대한 좋아요를 취소하는 기능입니다.
![image](https://github.com/user-attachments/assets/63cb5b88-a0ab-454b-b685-109ae8d08e1e)
좋아요가 이미되어있는 상태에서 /board/question/like/{id} 한번더 보내게되면 좋아요가 취소됩니다. 이미 구현되어있습니다.

3. 특정 게시물의 총 좋아요 수와 사용자가 해당 게시물을 좋아요 했는지 여부를 가져오는 기능
특정 게시물의 총 좋아요 수는 이미 사진과같이 총 좋아요 수가 나타나있고요 
![image](https://github.com/user-attachments/assets/6cffc1af-b824-45e2-9753-f2680cff4e6b)
사용자가 해당 게시글을 좋아요했는지 여부를 가져오는 기능은 뭐를 위해 필요한것인가요 ?
