### ISSUE TITLE
우빈이가 해줬으면 좋겠다

### ISSUE THREAD

**Issue by kyeongb-bin** [KJLBK/danum-backend#72]
### 어떤 문제?
> 1. 좋아요 버튼을 누르면 상태 변화만 하고 전체 좋아요 수는 가져올 수 없다.
> 2. 댓글 생성 500에러 뜨는데 이유는 잘 모르겠음 확인 부탁드리요.

### 해결 방안(참고)
> 좋아요 수를 get으로 보내주는 방법이 좋은 거 같다.

### 내가 코딩할 방법
> 좋아요 버튼을 누르면 put으로 좋아요 상태를 업데이트한 후에 성공하면 get으로 좋아요 수를 받아오기,
> 실패하면 에러 띄우기를 할 예정

### 아래 사진은 2번 문제 사진입니다.
<img width="1470" alt="스크린샷 2024-06-06 13 31 57" src="https://github.com/KJLBK/danum-backend/assets/154494689/6cd3f254-3cd6-42dc-bf75-bb675c77a231">

**Comment by KROOKIMWOOBIN** [comment]
### 문제 해결
> 좋아요를 요청할 시 반환 값 해당 ID에 전체 좋아요 수가 넘어가지도록 수정
